apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hpa
  namespace: argocd
spec:
  project: default
  destination: 
    namespace: hpa
    server: https://kubernetes.default.svc
  source:
    path: hpa
    repoURL: https://github.com/KevTamariz/example-hpa.git
    targetRevision: HEAD

# Scale: kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10


    