apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.8.2
