apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    path: myapp
    repoURL: https://github.com/applaudo-gcp-tp/ktamariz_W9_K8Code.git
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app